import { createContext, useContext, useState, ReactNode } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    // Hero
    "hero.badge": "Desarrollo de Software Premium",
    "hero.title": "Digital Excellence",
    "hero.subtitle": "Transformamos ideas en experiencias digitales excepcionales. Desarrollo profesional, diseño impecable.",
    "hero.cta.start": "Comenzar Proyecto",
    "hero.cta.portfolio": "Ver Trabajos",
    "hero.security": "100% Seguro",
    
    // Our Process
    "process.badge": "Nuestro Proceso",
    "process.title": "Cómo Trabajamos",
    "process.subtitle": "Un proceso claro y eficiente que garantiza resultados excepcionales en cada proyecto.",
    "process.discovery.title": "Descubrimiento",
    "process.discovery.desc": "Entendemos tu visión, objetivos y necesidades para crear una estrategia sólida.",
    "process.design.title": "Diseño UI/UX",
    "process.design.desc": "Creamos interfaces hermosas e intuitivas centradas en la experiencia del usuario.",
    "process.development.title": "Desarrollo",
    "process.development.desc": "Construimos tu proyecto con código limpio, escalable y las mejores tecnologías.",
    "process.launch.title": "Lanzamiento",
    "process.launch.desc": "Desplegamos tu proyecto y brindamos soporte continuo para tu éxito.",
    "process.cta.text": "¿Listo para comenzar tu proyecto?",
    "process.cta.button": "Agenda una Consulta Gratuita",
    
    // Services
    "services.badge": "Nuestros Servicios",
    "services.title": "Soluciones Completas",
    "services.subtitle": "Servicios profesionales de desarrollo con las últimas tecnologías y mejores prácticas.",
    "services.web.title": "Desarrollo Web",
    "services.web.desc": "Aplicaciones web modernas, rápidas y escalables.",
    "services.web.feature1": "React & Next.js",
    "services.web.feature2": "Node.js Backend",
    "services.web.feature3": "APIs RESTful",
    "services.web.feature4": "Progressive Web Apps",
    "services.mobile.title": "Apps Móviles",
    "services.mobile.desc": "Experiencias móviles nativas para iOS y Android.",
    "services.mobile.feature1": "React Native",
    "services.mobile.feature2": "Flutter",
    "services.mobile.feature3": "UI/UX Optimizado",
    "services.mobile.feature4": "Cross-platform",
    "services.cloud.title": "Cloud & DevOps",
    "services.cloud.desc": "Infraestructura escalable y automatizada.",
    "services.cloud.feature1": "AWS & Azure",
    "services.cloud.feature2": "Docker & Kubernetes",
    "services.cloud.feature3": "CI/CD Pipeline",
    "services.cloud.feature4": "Monitoring 24/7",
    "services.security.title": "Seguridad",
    "services.security.desc": "Protección integral de datos y aplicaciones.",
    "services.security.feature1": "SSL/TLS",
    "services.security.feature2": "OWASP Compliance",
    "services.security.feature3": "Penetration Testing",
    "services.security.feature4": "GDPR Ready",
    "services.performance.title": "Optimización",
    "services.performance.desc": "Rendimiento superior garantizado.",
    "services.performance.feature1": "CDN Global",
    "services.performance.feature2": "Cache Inteligente",
    "services.performance.feature3": "Lazy Loading",
    "services.performance.feature4": "Code Splitting",
    "services.database.title": "Bases de Datos",
    "services.database.desc": "Gestión de datos robusta y escalable.",
    "services.database.feature1": "PostgreSQL",
    "services.database.feature2": "MongoDB",
    "services.database.feature3": "Redis Cache",
    "services.database.feature4": "Data Analytics",
    "services.more": "Ver más",
    
    // Portfolio
    "portfolio.badge": "Nuestros Trabajos",
    "portfolio.title": "Proyectos Destacados",
    "portfolio.subtitle": "Soluciones digitales de alta calidad para diversos sectores e industrias.",
    "portfolio.view": "Ver Proyecto",
    "portfolio.code": "Ver Código",
    "portfolio.cta.text": "¿Tienes un proyecto en mente?",
    "portfolio.cta.button": "Conversemos →",
    
    // Portfolio Projects
    "portfolio.project1.title": "Aurum Capital",
    "portfolio.project1.desc": "Web para consultoría financiera con diseño elegante y confiable. Gráficos claros, enfoque en asesoría experta y gestión patrimonial estratégica.",
    "portfolio.project1.category": "Consultoría Financiera",
    "portfolio.project2.title": "Pixel Haus",
    "portfolio.project2.desc": "Web para estudio creativo con diseño muy visual y moderno. Énfasis en portafolio de trabajos y estética limpia que refleja creatividad.",
    "portfolio.project2.category": "Diseño Gráfico",
    "portfolio.project3.title": "GUSTO",
    "portfolio.project3.desc": "Web para restaurante premium con diseño elegante y apetitoso. Fotografías de alta calidad, menú claro y sistema de reservas integrado.",
    "portfolio.project3.category": "Gastronomía",
    "portfolio.project4.title": "Griega Propiedades",
    "portfolio.project4.desc": "Web para inmobiliaria con diseño moderno y visual. Destaca propiedades con imágenes de alta calidad y navegación intuitiva para encontrar tu hogar ideal.",
    "portfolio.project4.category": "Inmobiliaria",
    "portfolio.project5.title": "Constructora Alpha",
    "portfolio.project5.desc": "Web para constructora con diseño robusto y confiable. Muestra proyectos con galerías impactantes y testimonios, usando paleta de colores sólida.",
    "portfolio.project5.category": "Construcción",
    "portfolio.project6.title": "Clínica Sonrisaperfecta",
    "portfolio.project6.desc": "Web para clínica odontológica con diseño limpio y amigable. Información clara sobre servicios, equipo profesional y facilidad para agendar citas.",
    "portfolio.project6.category": "Salud Dental",
    
    // Bug Hunter Game
    "game.badge": "Zona Interactiva",
    "game.title": "Bug Hunter Challenge",
    "game.subtitle": "¿Tienes reflejos de desarrollador? Caza los bugs antes de que escapen, pero cuidado de no tocar el código correcto. 5 niveles de dificultad creciente.",
    "game.level": "Nivel",
    "game.score": "Puntos",
    "game.bugs": "Bugs Cazados",
    "game.time": "Tiempo",
    "game.start": "Comenzar Juego",
    "game.description": "Haz clic en los bugs 🐛 pero evita el código ✓.",
    "game.complete.levels": "Completa los 5 niveles para ganar.",
    "game.level.complete": "¡Nivel {level} Completado!",
    "game.next.level": "Siguiente Nivel →",
    "game.view.result": "Ver Resultado",
    "game.time.up": "¡Tiempo Agotado!",
    "game.reached.level": "Llegaste al nivel {level}",
    "game.total.score": "Puntos totales:",
    "game.play.again": "Jugar de Nuevo",
    "game.congratulations": "¡Felicitaciones!",
    "game.all.levels": "¡Completaste todos los niveles!",
    "game.final.score": "Puntuación final:",
    "game.instructions.bugs": "Haz clic en los bugs",
    "game.instructions.code": "Evita el código correcto",
    
    // Code Breaker Game
    "codebreaker.badge": "Desafío Extra",
    "codebreaker.title": "Code Breaker",
    "codebreaker.subtitle": "Descifra el código secreto de 4 dígitos. Usa la lógica y las pistas para encontrar la combinación correcta. ¡Tienes 10 intentos!",
    "codebreaker.attempts": "Intentos",
    "codebreaker.submit": "Verificar Código",
    "codebreaker.start": "Iniciar Desafío",
    "codebreaker.correct": "Correcto - Posición correcta",
    "codebreaker.present": "Presente - Posición incorrecta",
    "codebreaker.wrong": "Incorrecto - No está en el código",
    "codebreaker.won.title": "¡Código Descifrado!",
    "codebreaker.won.code": "Código secreto:",
    "codebreaker.won.attempts": "Lo lograste en {attempts} intentos",
    "codebreaker.lost.title": "¡Juego Terminado!",
    "codebreaker.lost.code": "El código secreto era:",
    "codebreaker.lost.message": "¡Sigue intentando!",
    
    // Contact
    "contact.badge": "Contacto",
    "contact.title": "Comencemos tu Proyecto",
    "contact.subtitle": "¿Tienes una idea? Estamos listos para convertirla en realidad. Contáctanos y recibe una consultoría gratuita.",
    "contact.info.title": "Información de Contacto",
    "contact.info.phone": "WhatsApp",
    "contact.info.whatsapp": "Contáctanos por WhatsApp",
    "contact.info.location": "Ubicación",
    "contact.social": "Síguenos en Instagram",
    "contact.trust.title": "Respuesta en 24h",
    "contact.trust.desc": "Garantizada o tu consulta gratis",
    "contact.form.name": "Nombre Completo",
    "contact.form.email": "Email",
    "contact.form.subject": "Asunto",
    "contact.form.message": "Mensaje",
    "contact.form.placeholder.name": "Tu nombre",
    "contact.form.placeholder.email": "tu@email.com",
    "contact.form.placeholder.subject": "¿En qué podemos ayudarte?",
    "contact.form.placeholder.message": "Cuéntanos sobre tu proyecto...",
    "contact.form.submit": "Enviar Mensaje",
    
    // Footer
    "footer.tagline": "Desarrollo de software profesional con diseño impecable.",
    "footer.services": "Servicios",
    "footer.services.web": "Desarrollo Web",
    "footer.services.mobile": "Apps Móviles",
    "footer.services.cloud": "Cloud & DevOps",
    "footer.services.consulting": "Consultoría IT",
    "footer.services.security": "Seguridad",
    "footer.company": "Empresa",
    "footer.company.about": "Sobre Nosotros",
    "footer.company.portfolio": "Portafolio",
    "footer.company.team": "Equipo",
    "footer.company.careers": "Carreras",
    "footer.company.blog": "Blog",
    "footer.resources": "Recursos",
    "footer.resources.docs": "Documentación",
    "footer.resources.cases": "Casos de Estudio",
    "footer.resources.api": "API Reference",
    "footer.resources.support": "Soporte",
    "footer.resources.contact": "Contacto",
    "footer.rights": "Todos los derechos reservados.",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
    "footer.cookies": "Cookies",
    "footer.powered": "Powered by AMR Technology",
  },
  en: {
    // Hero
    "hero.badge": "Premium Software Development",
    "hero.title": "Digital Excellence",
    "hero.subtitle": "We transform ideas into exceptional digital experiences. Professional development, impeccable design.",
    "hero.cta.start": "Start Project",
    "hero.cta.portfolio": "View Work",
    "hero.security": "100% Secure",
    
    // Our Process
    "process.badge": "Our Process",
    "process.title": "How We Work",
    "process.subtitle": "A clear and efficient process that guarantees exceptional results in every project.",
    "process.discovery.title": "Discovery",
    "process.discovery.desc": "We understand your vision, goals and needs to create a solid strategy.",
    "process.design.title": "UI/UX Design",
    "process.design.desc": "We create beautiful and intuitive interfaces focused on user experience.",
    "process.development.title": "Development",
    "process.development.desc": "We build your project with clean, scalable code and the best technologies.",
    "process.launch.title": "Launch",
    "process.launch.desc": "We deploy your project and provide ongoing support for your success.",
    "process.cta.text": "Ready to start your project?",
    "process.cta.button": "Schedule a Free Consultation",
    
    // Services
    "services.badge": "Our Services",
    "services.title": "Complete Solutions",
    "services.subtitle": "Professional development services with the latest technologies and best practices.",
    "services.web.title": "Web Development",
    "services.web.desc": "Modern, fast and scalable web applications.",
    "services.web.feature1": "React & Next.js",
    "services.web.feature2": "Node.js Backend",
    "services.web.feature3": "RESTful APIs",
    "services.web.feature4": "Progressive Web Apps",
    "services.mobile.title": "Mobile Apps",
    "services.mobile.desc": "Native mobile experiences for iOS and Android.",
    "services.mobile.feature1": "React Native",
    "services.mobile.feature2": "Flutter",
    "services.mobile.feature3": "Optimized UI/UX",
    "services.mobile.feature4": "Cross-platform",
    "services.cloud.title": "Cloud & DevOps",
    "services.cloud.desc": "Scalable and automated infrastructure.",
    "services.cloud.feature1": "AWS & Azure",
    "services.cloud.feature2": "Docker & Kubernetes",
    "services.cloud.feature3": "CI/CD Pipeline",
    "services.cloud.feature4": "24/7 Monitoring",
    "services.security.title": "Security",
    "services.security.desc": "Comprehensive data and application protection.",
    "services.security.feature1": "SSL/TLS",
    "services.security.feature2": "OWASP Compliance",
    "services.security.feature3": "Penetration Testing",
    "services.security.feature4": "GDPR Ready",
    "services.performance.title": "Optimization",
    "services.performance.desc": "Superior guaranteed performance.",
    "services.performance.feature1": "Global CDN",
    "services.performance.feature2": "Smart Caching",
    "services.performance.feature3": "Lazy Loading",
    "services.performance.feature4": "Code Splitting",
    "services.database.title": "Databases",
    "services.database.desc": "Robust and scalable data management.",
    "services.database.feature1": "PostgreSQL",
    "services.database.feature2": "MongoDB",
    "services.database.feature3": "Redis Cache",
    "services.database.feature4": "Data Analytics",
    "services.more": "Learn more",
    
    // Portfolio
    "portfolio.badge": "Our Work",
    "portfolio.title": "Featured Projects",
    "portfolio.subtitle": "High-quality digital solutions for various sectors and industries.",
    "portfolio.view": "View Project",
    "portfolio.code": "View Code",
    "portfolio.cta.text": "Have a project in mind?",
    "portfolio.cta.button": "Let's Talk →",
    
    // Portfolio Projects
    "portfolio.project1.title": "Aurum Capital",
    "portfolio.project1.desc": "Financial consulting website with elegant and reliable design. Clear graphics, focus on expert advice and strategic wealth management.",
    "portfolio.project1.category": "Financial Consulting",
    "portfolio.project2.title": "Pixel Haus",
    "portfolio.project2.desc": "Creative studio website with highly visual and modern design. Emphasis on work portfolio and clean aesthetic that reflects creativity.",
    "portfolio.project2.category": "Graphic Design",
    "portfolio.project3.title": "GUSTO",
    "portfolio.project3.desc": "Premium restaurant website with elegant and appetizing design. High-quality photography, clear menu and integrated reservation system.",
    "portfolio.project3.category": "Gastronomy",
    "portfolio.project4.title": "Griega Properties",
    "portfolio.project4.desc": "Real estate website with modern and visual design. Highlights properties with high-quality images and intuitive navigation to find your ideal home.",
    "portfolio.project4.category": "Real Estate",
    "portfolio.project5.title": "Constructora Alpha",
    "portfolio.project5.desc": "Construction company website with robust and reliable design. Showcases projects with impressive galleries and testimonials, using solid color palette.",
    "portfolio.project5.category": "Construction",
    "portfolio.project6.title": "Sonrisaperfecta Clinic",
    "portfolio.project6.desc": "Dental clinic website with clean and friendly design. Clear information about services, professional team and easy appointment scheduling.",
    "portfolio.project6.category": "Dental Health",
    
    // Bug Hunter Game
    "game.badge": "Interactive Zone",
    "game.title": "Bug Hunter Challenge",
    "game.subtitle": "Got developer reflexes? Hunt the bugs before they escape, but be careful not to touch the correct code. 5 levels of increasing difficulty.",
    "game.level": "Level",
    "game.score": "Score",
    "game.bugs": "Bugs Hunted",
    "game.time": "Time",
    "game.start": "Start Game",
    "game.description": "Click on the bugs 🐛 but avoid the code ✓.",
    "game.complete.levels": "Complete all 5 levels to win.",
    "game.level.complete": "Level {level} Complete!",
    "game.next.level": "Next Level →",
    "game.view.result": "View Result",
    "game.time.up": "Time's Up!",
    "game.reached.level": "You reached level {level}",
    "game.total.score": "Total score:",
    "game.play.again": "Play Again",
    "game.congratulations": "Congratulations!",
    "game.all.levels": "You completed all levels!",
    "game.final.score": "Final score:",
    "game.instructions.bugs": "Click on the bugs",
    "game.instructions.code": "Avoid the correct code",
    
    // Code Breaker Game
    "codebreaker.badge": "Extra Challenge",
    "codebreaker.title": "Code Breaker",
    "codebreaker.subtitle": "Crack the secret 4-digit code. Use logic and clues to find the right combination. You have 10 attempts!",
    "codebreaker.attempts": "Attempts",
    "codebreaker.submit": "Check Code",
    "codebreaker.start": "Start Challenge",
    "codebreaker.correct": "Correct - Right position",
    "codebreaker.present": "Present - Wrong position",
    "codebreaker.wrong": "Wrong - Not in code",
    "codebreaker.won.title": "Code Cracked!",
    "codebreaker.won.code": "Secret code:",
    "codebreaker.won.attempts": "You did it in {attempts} attempts",
    "codebreaker.lost.title": "Game Over!",
    "codebreaker.lost.code": "The secret code was:",
    "codebreaker.lost.message": "Keep trying!",
    
    // Contact
    "contact.badge": "Contact",
    "contact.title": "Let's Start Your Project",
    "contact.subtitle": "Have an idea? We're ready to make it reality. Contact us and get a free consultation.",
    "contact.info.title": "Contact Information",
    "contact.info.phone": "WhatsApp",
    "contact.info.whatsapp": "Contact us on WhatsApp",
    "contact.info.location": "Location",
    "contact.social": "Follow Us on Instagram",
    "contact.trust.title": "24h Response",
    "contact.trust.desc": "Guaranteed or your consultation free",
    "contact.form.name": "Full Name",
    "contact.form.email": "Email",
    "contact.form.subject": "Subject",
    "contact.form.message": "Message",
    "contact.form.placeholder.name": "Your name",
    "contact.form.placeholder.email": "your@email.com",
    "contact.form.placeholder.subject": "How can we help you?",
    "contact.form.placeholder.message": "Tell us about your project...",
    "contact.form.submit": "Send Message",
    
    // Footer
    "footer.tagline": "Professional software development with impeccable design.",
    "footer.services": "Services",
    "footer.services.web": "Web Development",
    "footer.services.mobile": "Mobile Apps",
    "footer.services.cloud": "Cloud & DevOps",
    "footer.services.consulting": "IT Consulting",
    "footer.services.security": "Security",
    "footer.company": "Company",
    "footer.company.about": "About Us",
    "footer.company.portfolio": "Portfolio",
    "footer.company.team": "Team",
    "footer.company.careers": "Careers",
    "footer.company.blog": "Blog",
    "footer.resources": "Resources",
    "footer.resources.docs": "Documentation",
    "footer.resources.cases": "Case Studies",
    "footer.resources.api": "API Reference",
    "footer.resources.support": "Support",
    "footer.resources.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.cookies": "Cookies",
    "footer.powered": "Powered by AMR Technology",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("es");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.es] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
